### ISSUE TITLE
gtk support?

### ISSUE THREAD

**Issue by xFedee** [Luwx/Lightly#193]
gtk support

**Comment by CavaleriOmar** [comment]
Maybe that it would also respect the pixel value chosen for button corners (and colors, as breeze-gtk already does).

That would be so cool because it would solve a lot of problems.

Until I don't know how many updates ago (I don't remember if it was the last version of plasma 5.24 or if it was one of the first of 5.25) breeze-gtk respected both color and appearance (whether it was breeze, kvantum or lightly).
