### ISSUE TITLE
Clicking Dolphin's Folder Share tab instantly crashes 

### ISSUE THREAD

**Issue by Goodname15** [Luwx/Lightly#194]
To be able to encounter this issue, kdenetwork-filesharing needs to be installed.
I personally also have the latest github version installed on Fedora Workstation 36 with KDE.
The issue does not appear when using Breeze instead of Lightly.

When clicking on the Share tab of Folder properties, dolphin crashes
![image](https://user-images.githubusercontent.com/68472329/194755182-f9f732e2-d2c5-45fa-9468-849ed3458082.png)

Here's the Crash Log:
https://pastebin.com/D2ykBDYP

**Comment by boehs** [comment]
![2022-10-09_16-05](https://user-images.githubusercontent.com/51836263/194777322-39476baa-5366-4680-82c7-9fa308d051c8.png)

Can't reproduce, at least on https://github.com/boehs/lightly (in which none of the changes I imagine would affect this)

Do you have any other reproduction steps?

**Comment by Goodname15** [comment]
Sadly, I do not. I've tried https://github.com/boehs/lightly but the same issue persists. It really just is an instant crash of dolphin when clicking the share tab while having lightly active and I have no idea why it would not be reproducible on your system.

**Comment by pizzadude** [comment]
I had the same issue. I fixed it by building the latest fork from source. But for some reason, building the latest fork from source manually (sudo make install), I couldn't apply the theme. So I took the fedora spec for lightly and adapted it to work with the latest git version of the fork:

https://github.com/pizzadude/kdestuff-copr/blob/main/lightly-git.spec

And it works! But if you are lazy and you don't want to manually build an RPM file from that spec I just linked, you can get it from here:

https://copr.fedorainfracloud.org/coprs/pizzadude/kdestuff/

The package is lightly-git.

Edit: Basically what I'm saying is, I needed to build an RPM instead of building via traditional methods for it to let me install lightly from source. I recommend you grab my spec file and build it yourself also.

**Comment by Goodname15** [comment]
Just tried it and it works! I don't really understand, what makes your method different from just installing normally, which did work for me, when I first installed lightly from dnf and then built the new version. But for some reason it is different, so thanks!
