### ISSUE TITLE
Konsole inactive tabs do not have blur

### ISSUE THREAD

**Issue by ryu-ketsueki** [Luwx/Lightly#47]
![image](https://user-images.githubusercontent.com/39316730/106783837-799e2900-662a-11eb-862b-9a7036cc6368.png)
I just updated to master to apply the changes done to tabs and I noticed this on Konsole. The inactive tabs do not have blurred background to match with the titlebar
And as minor bug, the New Tab Button is opaque. Not sure how hard it is to make it transparent like the inactive tabs but it could be something good for sake of visual consistency. It also happens for when the tabs are not max width.
![image](https://user-images.githubusercontent.com/39316730/106784341-ffba6f80-662a-11eb-94ab-0d55251112ab.png)

**Comment by Luwx** [comment]
That's intentional, Lightly and Konsole have a deep conflict over the blur effect, and I choose to disable it for konsole, this means that you have to enable the blur in the konsole color editor.

About the opaque parts in the tab bar, there is an option in Lightly settings called "Unify konsole tab bar with header area", but it will only work well if there is no new tab button and if the tabs expand to the full window width. You can uncheck this option to return to the old behavior:

![image](https://user-images.githubusercontent.com/33076480/106794451-a0169100-6637-11eb-92b6-06d038e81823.png)

Perhaps I'll make it disabled by default.

**Comment by ryu-ketsueki** [comment]
Right. I forgot about the option of blur in the colors. And regarding the tab bar not being transparent (explaining why the new tab button is not with a transparent background), there is nothing that can be done about it, right? Other than removing the new tab button and set the tabs to full width, I mean.
