### ISSUE TITLE
Cannot compile Lightly

### ISSUE THREAD

**Issue by gianmarcogg03** [Luwx/Lightly#68]
I've followed the manual installation guide (since I'm on Arch) perfectly but at `make` I get these errors that prevent me from compiling the theme.
![image](https://user-images.githubusercontent.com/28053717/107849904-8d057d00-6dfe-11eb-8d2e-7a58a14d8b6f.png)

**Comment by Luki72** [comment]
Hi,

the same here on Debian testing. Here is the output of cmake (maybe this will help):

-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Setting build type to 'Debug' as none was specified.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.78.0") 
-- Found KF5GuiAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (found version "5.78.0") 
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.78.0") 
-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.78.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.78.0") 
-- Found KF5IconThemes: /usr/lib/x86_64-linux-gnu/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.78.0") 
-- Found KF5: success (found version "5.78.0") found components: CoreAddons GuiAddons ConfigWidgets WindowSystem I18n IconThemes 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.14") 
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.14") found components: XCB 
-- Warning: Property URL already set to "https://xcb.freedesktop.org/", overriding it with "https://xcb.freedesktop.org"
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found KF5Config: /usr/lib/x86_64-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.78.0") 
-- Found KF5: success (found version "5.78.0") found components: I18n Config GuiAddons IconThemes ConfigWidgets WindowSystem 
-- Could NOT find KF5FrameworkIntegration (missing: KF5FrameworkIntegration_DIR)
-- Warning: Property URL already set to "https://xcb.freedesktop.org", overriding it with "https://xcb.freedesktop.org/"
-- Warning: Property URL already set to "https://xcb.freedesktop.org/", overriding it with "https://xcb.freedesktop.org"
-- Could NOT find KF5Wayland (missing: KF5Wayland_DIR)
-- Could NOT find KF5KCMUtils (missing: KF5KCMUtils_DIR)
-- Found KF5: success (found version "5.78.0") found components: CoreAddons Config 
CMake Warning (dev) at /usr/share/ECM/modules/ECMPackageConfigHelpers.cmake:63 (message):
  Your project already requires a version of CMake that includes the
  find_dependency macro via the CMakeFindDependencyMacro module.  You should
  use CMakePackageConfigHelpers instead of ECMPackageConfigHelpers.
Call Stack (most recent call first):
  misc/kde4lightly/CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The following OPTIONAL packages have been found:

 * KF5Auth (required version >= 5.78.0)
 * KF5Codecs (required version >= 5.78.0)
 * KF5WidgetsAddons (required version >= 5.78.0)
 * Qt5Network (required version >= 5.15.2)
 * Qt5Qml (required version >= 5.15.2)
 * Qt5QmlModels (required version >= 5.15.2)
 * Qt5Quick
 * PkgConfig
 * XCB, X protocol C-language Binding, <https://xcb.freedesktop.org>
   Required to pass style properties to native Windows on X11 Platform
   Required to pass style properties to native Windows on X11 Platform
 * Qt5Core (required version >= 5.14.0)

-- The following REQUIRED packages have been found:

 * KDecoration2
 * Gettext
 * KF5I18n
 * KF5GuiAddons
 * KF5IconThemes
 * KF5ConfigWidgets
 * KF5WindowSystem
 * Qt5X11Extras
 * ECM (required version >= 0.0.13)
 * Qt5Widgets
 * Qt5
 * KF5CoreAddons
 * Qt5DBus (required version >= 5.14.0)
 * KF5Config
 * KF5

-- The following OPTIONAL packages have not been found:

 * KF5FrameworkIntegration, KF5 Framework Integration, <https://projects.kde.org/projects/frameworks/frameworkintegration>
   Required to use KStyle convenience functionalities in style
 * KF5Wayland
 * KF5KCMUtils, KF5 KCM utils Framework, <https://projects.kde.org/projects/frameworks/kcmutils>
   Required for lightly-settings5 application to build

-- Configuring done
-- Generating done
-- Build files have been written to: /home/luki/Git/Lightly/build

**Comment by Luki72** [comment]
Hi,

the same here on Debian testing.

```
Scanning dependencies of target lightlycommon5_autogen
[  1%] Automatic MOC for target lightlycommon5
[  1%] Built target lightlycommon5_autogen
Scanning dependencies of target lightlycommon5
[  2%] Building CXX object liblightlycommon/CMakeFiles/lightlycommon5.dir/lightlycommon5_autogen/mocs_compilation.cpp.o
[  3%] Building CXX object liblightlycommon/CMakeFiles/lightlycommon5.dir/lightlyboxshadowrenderer.cpp.o
[  4%] Linking CXX shared library ../bin/liblightlycommon5.so
CMake Error: failed to create symbolic link '../bin/liblightlycommon5.so.5': operation not supported on socket
CMake Error: cmake_symlink_library: System Error: Operation not supported
CMake Error: failed to create symbolic link '../bin/liblightlycommon5.so': operation not supported on socket
CMake Error: cmake_symlink_library: System Error: Operation not supported
make[2]: *** [liblightlycommon/CMakeFiles/lightlycommon5.dir/build.make:119: bin/liblightlycommon5.so.5.19.4] Error 1
make[2]: *** Deleting file 'bin/liblightlycommon5.so.5.19.4'
make[1]: *** [CMakeFiles/Makefile2:677: liblightlycommon/CMakeFiles/lightlycommon5.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Here is the output of cmake (maybe this will help):

```
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Setting build type to 'Debug' as none was specified.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.78.0") 
-- Found KF5GuiAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (found version "5.78.0") 
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.78.0") 
-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.78.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.78.0") 
-- Found KF5IconThemes: /usr/lib/x86_64-linux-gnu/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.78.0") 
-- Found KF5: success (found version "5.78.0") found components: CoreAddons GuiAddons ConfigWidgets WindowSystem I18n IconThemes 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.14") 
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.14") found components: XCB 
-- Warning: Property URL already set to "https://xcb.freedesktop.org/", overriding it with "https://xcb.freedesktop.org"
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found KF5Config: /usr/lib/x86_64-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.78.0") 
-- Found KF5: success (found version "5.78.0") found components: I18n Config GuiAddons IconThemes ConfigWidgets WindowSystem 
-- Could NOT find KF5FrameworkIntegration (missing: KF5FrameworkIntegration_DIR)
-- Warning: Property URL already set to "https://xcb.freedesktop.org", overriding it with "https://xcb.freedesktop.org/"
-- Warning: Property URL already set to "https://xcb.freedesktop.org/", overriding it with "https://xcb.freedesktop.org"
-- Could NOT find KF5Wayland (missing: KF5Wayland_DIR)
-- Could NOT find KF5KCMUtils (missing: KF5KCMUtils_DIR)
-- Found KF5: success (found version "5.78.0") found components: CoreAddons Config 
CMake Warning (dev) at /usr/share/ECM/modules/ECMPackageConfigHelpers.cmake:63 (message):
  Your project already requires a version of CMake that includes the
  find_dependency macro via the CMakeFindDependencyMacro module.  You should
  use CMakePackageConfigHelpers instead of ECMPackageConfigHelpers.
Call Stack (most recent call first):
  misc/kde4lightly/CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The following OPTIONAL packages have been found:

 * KF5Auth (required version >= 5.78.0)
 * KF5Codecs (required version >= 5.78.0)
 * KF5WidgetsAddons (required version >= 5.78.0)
 * Qt5Network (required version >= 5.15.2)
 * Qt5Qml (required version >= 5.15.2)
 * Qt5QmlModels (required version >= 5.15.2)
 * Qt5Quick
 * PkgConfig
 * XCB, X protocol C-language Binding, <https://xcb.freedesktop.org>
   Required to pass style properties to native Windows on X11 Platform
   Required to pass style properties to native Windows on X11 Platform
 * Qt5Core (required version >= 5.14.0)

-- The following REQUIRED packages have been found:

 * KDecoration2
 * Gettext
 * KF5I18n
 * KF5GuiAddons
 * KF5IconThemes
 * KF5ConfigWidgets
 * KF5WindowSystem
 * Qt5X11Extras
 * ECM (required version >= 0.0.13)
 * Qt5Widgets
 * Qt5
 * KF5CoreAddons
 * Qt5DBus (required version >= 5.14.0)
 * KF5Config
 * KF5

-- The following OPTIONAL packages have not been found:

 * KF5FrameworkIntegration, KF5 Framework Integration, <https://projects.kde.org/projects/frameworks/frameworkintegration>
   Required to use KStyle convenience functionalities in style
 * KF5Wayland
 * KF5KCMUtils, KF5 KCM utils Framework, <https://projects.kde.org/projects/frameworks/kcmutils>
   Required for lightly-settings5 application to build

-- Configuring done
-- Generating done
-- Build files have been written to: /home/luki/Git/Lightly/build

```

**Comment by Luwx** [comment]
This seems related to filesystem/mounting problems, are you using anything unusual? Does the same thing happen when you try to compile https://github.com/KDE/breeze ?

**Comment by Luki72** [comment]
> This seems related to filesystem/mounting problems, are you using anything unusual? Does the same thing happen when you try to compile https://github.com/KDE/breeze ?

Yesss! You're absolutely right. In my case: the Git folder was mounted from my server via Samba, so moving it to the local disk solved the problem.
THX
