### ISSUE TITLE
Size of items on lower resolutions

### ISSUE THREAD

**Issue by ryu-ketsueki** [Luwx/Lightly#76]
Would it be possible to include an option that shrinks the height of items in the context menu and possibly tabs so they are more friendly with lower resolution screens? Many laptops are still limited to a 1366x768 resolution and several windows look too big. I noticed that the height of items on a context menu is higher than on Mac, for example.

**Comment by Martchus** [comment]
I'd appreciate that as well as I also still have a 1366x768 resolution laptop.

**Comment by Luwx** [comment]
I'll reduce a bit the menu item size, but there is a bigger issue with Lightly, that in order to have nice shadows around widgets (buttons, lineedits, views) I have to increase the widget size, and this makes everything have larger than needed margins, it's especially evident in Kcalc, the buttons look small and there is a lot of space between them. Perhaps in the future, I'll add an option to configure the widget shadow size.

**Comment by Luwx** [comment]
The checkbox, context menu and tabs are a little more compact now.
