### ISSUE TITLE
two screen bug 

### ISSUE THREAD

**Issue by Taza53** [Luwx/Lightly#79]
![image](https://user-images.githubusercontent.com/34032665/108695471-9ed2d880-7500-11eb-8625-8743f4a08c3c.png)

This it what it normally looks like and what it is suppose to be. but when the application is in any position the menu might touch the top or bottom of the screen it will move to the screen.

![image](https://user-images.githubusercontent.com/34032665/108695726-ea858200-7500-11eb-8e36-0543fa797724.png)

![image](https://user-images.githubusercontent.com/34032665/108696172-7c8d8a80-7501-11eb-97bb-397811439406.png)

left screen is 1080p the right screen is 2k.

**Comment by Taza53** [comment]
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.15-1-MANJARO
OS Type: 64-bit

**Comment by TobiPeterG** [comment]
I have a 1080p and 4K monitor on OpenSUSE, everything works fine here.
What graphics card do you have and which compositor settings?

**Comment by Taza53** [comment]
vega 56. opengl 3.1.
I have changed the compositor it still happens.
so can you test it by placing dolphin in a position when you press the option button, the menu bar should be able to touch the top or the bottom of the screen. So basically what as the menu bar can't fully go top or bottom it jumps to the other screen.
Please let me know if it is just a me problem thx.

**Comment by Luwx** [comment]
I have the same problem with Breeze: 

![Screenshot_20210224_183417](https://user-images.githubusercontent.com/33076480/109068790-15253580-76cf-11eb-9113-96038d4c6057.png)

This seems unrelated to the style and more with the window manager. It's triggered when the menu height is bigger than half screen height and it's position overlaps with the mouse. Since Lightly context menus are taller than Breeze, the problem is accentuated, but there is not much I can do.
