### ISSUE TITLE
Dolphin background opacity

### ISSUE THREAD

**Issue by edpil02** [Luwx/Lightly#97]
After enable  "Transparent dolphin view" is there a way to adjust  dolphin background opacity ?
I made a search in lightlystyle.cpp   but i'm not a progammer and dont totally understand the code.
Thanks.

**Comment by edpil02** [comment]
Sorry .
Issue  partially  solves after reading that :

You'll have to change the current color scheme (~/.local/share/color-schemes) for that , in the [Colors:Window] section, add a fourth value to BackgroundNormal, that is the transparency. I don't know if this will work if you are not running plasma, because Lightly, like breeze, still depends a lot on kde stuff.

**Comment by Sadi58** [comment]
I've modified the Lightly color-scheme at `/usr/share/color-schemes` , adding a fourth transparency value of 0.35 at the end of `BackgroundNormal` in `[Colors:Window]` section, but it didn't have any effect as far as I can see - under KDE neon.

I'd also like to add a little transparency to the Dolphin window, although less than side panels to the left and right.

**Comment by doncsugar** [comment]
@Sadi58 I would not recommend editing root color schemes. It would be better to go to Colors in System Settings, click the edit button on Lightly, and then save that as a new color scheme. It will be in `~/.local/share/color-schemes/`

In order to make windows translucent you have to pass an _opacity_ value in the 0-255 range (0 is completely transparent, 255 is completely opaque). Multiply your opacity by 255 to get the integer value.

For 0.35: `0.35 * 255 = 89.25` -> **89** is what you want.

In the `.colors` file:
```
[Colors:Window]
BackgroundAlternate=227,229,231
BackgroundNormal=246,246,246,89
```
In the above, I added `,89` to `BackgroundNormal`


Remember, glass themes are still unsupported and buggy.

**Comment by mdhishamsayed** [comment]
@doncsugar dude looks like ur an expert in kde..
can you set this color scheme also transparent
[Invent.txt](https://github.com/Luwx/Lightly/files/8592006/Invent.txt)
?

**Comment by doncsugar** [comment]
@mdhishamsayed The directions for a transparent titlebar are under **Configuration** in the [README.md](https://github.com/Luwx/Lightly#configuration). Under `[WM]`, add the 4th value to `activeBackground` and `inactiveBackground`.
